# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakadash" do
  name "wakadash"
  desc "Live terminal dashboard for WakaTime coding stats"
  homepage "https://github.com/b00y0h/wakadash"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakadash"

  on_macos do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_amd64.tar.gz"
      sha256 "d54b17236a761562afd9f4d161e6ca8844b7b3f2d43258d04f956e4b57b73fd7"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_arm64.tar.gz"
      sha256 "9d7c135896632b0be2ce3368420ec2d807439db4387b5ffb71b29fcae64ba160"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_amd64.tar.gz"
      sha256 "d62b3d7fd5da0bda20641a6f791b0ef847a1871a1b8296f22a8595a850a39ea3"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_arm64.tar.gz"
      sha256 "bb1958735fa2ec02d7913525c38d6d8bb12acaed7d8a8b6c8bc6f85d518b59be"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakadash"]
    end
  end

  # No zap stanza required
end
