# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakadash" do
  name "wakadash"
  desc "Live terminal dashboard for WakaTime coding stats"
  homepage "https://github.com/b00y0h/wakadash"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakadash"

  on_macos do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_amd64.tar.gz"
      sha256 "eb67a2fcff4a3612cbf3d00de71046216e444fb2b036eccb703d7f3d16e7d384"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_arm64.tar.gz"
      sha256 "c4387948f4f69d929fb3c573d26967d6827ec2ec0d4799ad073cccb95c520358"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_amd64.tar.gz"
      sha256 "089e96fa99f7f52cd89e771821e2c5f2040140a9a13fade33c68ba4ae90fc9fc"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_arm64.tar.gz"
      sha256 "38fe2e2ca3dd9935ca847e2c72589e3d9cbca702ca9e218ac04e634b8e34642d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakadash"]
    end
  end

  # No zap stanza required
end
