# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakadash" do
  name "wakadash"
  desc "Live terminal dashboard for WakaTime coding stats"
  homepage "https://github.com/b00y0h/wakadash"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakadash"

  on_macos do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_amd64.tar.gz"
      sha256 "a58dbc80b5d2a07d30a24935d86f73484a6440f12bbe7758b6ce8ca053a04ec0"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_darwin_arm64.tar.gz"
      sha256 "0e82e7c7919861d1dc2b8c3a86472fb0c9eba2c787c91cd5af590ebe0b3f18a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_amd64.tar.gz"
      sha256 "b7429b376844df6d90d6f950e592a718bd0b50f7ae5697abb2b7c62102c7e79d"
    end
    on_arm do
      url "https://github.com/b00y0h/wakadash/releases/download/v#{version}/wakadash_#{version}_linux_arm64.tar.gz"
      sha256 "ffaa609367cc6cfcc071d2705c3060e8d6862eb160063df2e7f6ff8bb542840b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakadash"]
    end
  end

  # No zap stanza required
end
